'use client';
import {useEffect,useMemo,useState} from 'react';
import {useParams,useRouter} from 'next/navigation';
import {api,getUser} from '../../../lib/api';
export default function EventDetail(){const {id}=useParams();const router=useRouter();const [event,setEvent]=useState<any>();const [seats,setSeats]=useState<any[]>([]);const [selected,setSelected]=useState<number>();const [error,setError]=useState('');const [message,setMessage]=useState('');
async function load(){setEvent(await api(`/events/${id}`));setSeats(await api(`/events/${id}/seats`))}useEffect(()=>{load();const ws=new WebSocket(`${(process.env.NEXT_PUBLIC_API_URL||'http://localhost:8000').replace(/^http/, 'ws')}/ws/events/${id}/seats`);ws.onmessage=(m)=>{const p=JSON.parse(m.data);if(p.seat_id)setSeats(s=>s.map(x=>x.id===p.seat_id?{...x,status:p.status}:x))};return()=>ws.close()},[id]);
const rows=useMemo(()=>{const map:any={};seats.forEach(s=>(map[s.row]??=[]).push(s));return map},[seats]);if(!event)return <div className="card">Carregando…</div>;
async function reserve(payment:string){if(!getUser()){router.push('/login');return}if(!selected){setError('Escolha um assento.');return}setError('');setMessage('');try{const r=await api('/reservations',{method:'POST',body:JSON.stringify({seat_id:selected,payment})});if(r.status==='cancelled'){setError('Pagamento recusado. O lugar voltou ao estoque.');return}setMessage('Pagamento aprovado. Ingresso criado.');setTimeout(()=>router.push('/tickets'),600)}catch(e:any){setError(e.message);load()}}
return <><div className="hero"><div><div className="eyebrow">Evento</div><h1>{event.title}</h1><p className="muted">{event.location} · {new Date(event.starts_at).toLocaleString('pt-BR')}</p></div><div className="card"><div className="price">R$ {(event.price_cents/100).toFixed(2)}</div><p className="muted">por assento</p></div></div><div className="card"><div className="screen">TELA / PALCO</div>{Object.entries(rows).map(([row,arr]:any)=><div key={row} className="row" style={{justifyContent:'flex-start',marginBottom:7}}><b style={{width:24}}>{row}</b>{arr.map((s:any)=><button key={s.id} disabled={s.status!=='available'} onClick={()=>setSelected(s.id)} className={`seat ${s.status!=='available'?'taken':''} ${selected===s.id?'selected':''}`}>{s.number}</button>)}</div>)}<div className="row" style={{marginTop:20}}><div>{selected?<b>Selecionado: {seats.find(s=>s.id===selected)?.label}</b>:<span className="muted">Selecione um lugar</span>}</div><div className="row"><button className="btn primary" onClick={()=>reserve('approve')}>Pagar simulado</button><button className="btn ghost" onClick={()=>reserve('decline')}>Simular recusa</button></div></div>{error&&<div className="status bad" style={{marginTop:16}}>{error}</div>}{message&&<div className="status ok" style={{marginTop:16}}>{message}</div>}</div></>}
